name: rawnaq
description: "Rawnaq - Project management platform for interior design teams and operational staff."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^13.2.0
  
  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  responsive_builder: ^0.7.0
  syncfusion_flutter_charts: ^30.1.37
  gantt_chart: ^0.3.0
  image_picker: ^1.0.7
  file_picker: ^8.1.4
  web: ^1.1.1
  url_launcher: ^6.2.5
  crop_your_image: ^2.0.0
  image: ^4.1.7
  
  # Audio
  audioplayers: ^6.0.0
  
  
  # Tree View and Hierarchical UI
  flutter_treeview: ^1.0.7+1
  flutter_reorderable_list: ^1.0.0
  expandable: ^5.0.1
  
  # Utils
  intl: ^0.20.2
  dartz: ^0.10.1
  get_it: ^7.6.7
  easy_debounce: ^2.0.3
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^17.2.1
  
  # Dependency Injection
  injectable: ^2.3.2
  
  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  
  # App Icon Generator
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
